export enum Role {
  STAFF = 'STAFF',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  HR = 'HR',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  LATE = 'LATE',
  ABSENT = 'ABSENT',
  HALF_DAY = 'HALF_DAY',
  ON_LEAVE = 'ON_LEAVE',
  HOLIDAY = 'HOLIDAY',
  WEEKEND = 'WEEKEND',
}

export enum LeaveType {
  CASUAL = 'CASUAL',
  SICK = 'SICK',
  EARNED = 'EARNED',
  MATERNITY = 'MATERNITY',
  PATERNITY = 'PATERNITY',
  UNPAID = 'UNPAID',
  PAID = 'PAID',
  EMERGENCY = 'EMERGENCY',
}

export enum LeaveStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum HolidayType {
  NATIONAL = 'NATIONAL',
  FESTIVAL = 'FESTIVAL',
  SCHOOL = 'SCHOOL',
  VACATION = 'VACATION',
}

export enum NotificationType {
  ATTENDANCE_REMINDER = 'ATTENDANCE_REMINDER',
  MEETING_NOTICE = 'MEETING_NOTICE',
  HOLIDAY_NOTICE = 'HOLIDAY_NOTICE',
  LEAVE_APPROVAL = 'LEAVE_APPROVAL',
  LEAVE_REJECTION = 'LEAVE_REJECTION',
  GENERAL_CIRCULAR = 'GENERAL_CIRCULAR',
}
