import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  FlatList,
  TouchableOpacity,
  Modal,
  ScrollView,
  ActivityIndicator,
  RefreshControl,
} from 'react-native';
import {
  FileText,
  Calendar,
  CheckCircle2,
  Clock,
  ChevronRight,
  X,
  Building,
  User,
  DollarSign,
} from 'lucide-react-native';
import { Colors, typography } from '../../../theme';
import AppHeader from '../../../components/common/AppHeader';
import { salaryService, SalarySlipItem } from '../../../services/salaryService';
import { showToast } from '../../../utils/toast';

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

export default function SalarySlipScreen() {
  const [slips, setSlips] = useState<SalarySlipItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [selectedSlip, setSelectedSlip] = useState<SalarySlipItem | null>(null);

  const fetchSlips = async () => {
    try {
      const data = await salaryService.getMySalarySlips();
      setSlips(data || []);
    } catch (err: any) {
      showToast.error('Error', err?.message || 'Failed to fetch salary slips.');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchSlips();
  }, []);

  const handleRefresh = () => {
    setRefreshing(true);
    fetchSlips();
  };

  const renderSlipCard = ({ item }: { item: SalarySlipItem }) => {
    const isPaid = item.status === 'PAID';
    const monthName = MONTH_NAMES[item.month - 1] || `Month ${item.month}`;

    return (
      <TouchableOpacity
        style={styles.card}
        activeOpacity={0.8}
        onPress={() => setSelectedSlip(item)}
      >
        <View style={styles.cardHeader}>
          <View style={styles.monthBadge}>
            <Calendar size={16} color={Colors.primary} style={{ marginRight: 6 }} />
            <Text style={styles.monthText}>{monthName} {item.year}</Text>
          </View>
          <View style={[styles.statusBadge, isPaid ? styles.paidBadge : styles.pendingBadge]}>
            {isPaid ? (
              <CheckCircle2 size={12} color="#10B981" style={{ marginRight: 4 }} />
            ) : (
              <Clock size={12} color="#F59E0B" style={{ marginRight: 4 }} />
            )}
            <Text style={[styles.statusText, isPaid ? styles.paidText : styles.pendingText]}>
              {item.status}
            </Text>
          </View>
        </View>

        <View style={styles.cardBody}>
          <View style={styles.amountContainer}>
            <Text style={styles.amountLabel}>Net Payable Salary</Text>
            <Text style={styles.amountValue}>₹{item.netSalary.toLocaleString('en-IN')}</Text>
          </View>

          <View style={styles.statsRow}>
            <Text style={styles.statText}>
              Present: <Text style={styles.statHighlight}>{item.presentDays} Days</Text>
            </Text>
            <Text style={styles.statDot}>•</Text>
            <Text style={styles.statText}>
              Unpaid Cut: <Text style={[styles.statHighlight, { color: Colors.error }]}>{item.unpaidLeaveDays + item.absentDays} Days</Text>
            </Text>
          </View>
        </View>

        <View style={styles.cardFooter}>
          <Text style={styles.viewDetailText}>Tap to view full salary slip breakdown</Text>
          <ChevronRight size={16} color={Colors.primary} />
        </View>
      </TouchableOpacity>
    );
  };

  return (
    <View style={styles.container}>
      <AppHeader title="My Salary Slips" showBack />

      {loading ? (
        <View style={styles.centerContainer}>
          <ActivityIndicator size="large" color={Colors.primary} />
          <Text style={styles.loadingText}>Loading Salary Slips...</Text>
        </View>
      ) : (
        <FlatList
          data={slips}
          keyExtractor={(item) => item.id}
          renderItem={renderSlipCard}
          contentContainerStyle={styles.listContent}
          refreshControl={
            <RefreshControl refreshing={refreshing} onRefresh={handleRefresh} colors={[Colors.primary]} />
          }
          ListEmptyComponent={
            <View style={styles.emptyContainer}>
              <FileText size={48} color={Colors.textDisabled} />
              <Text style={styles.emptyTitle}>No Salary Slips Issued</Text>
              <Text style={styles.emptySubtitle}>
                Your monthly salary slips generated by school administration will appear here.
              </Text>
            </View>
          }
        />
      )}

      {/* FULL SALARY SLIP DETAIL MODAL */}
      <Modal
        visible={!!selectedSlip}
        animationType="slide"
        transparent
        onRequestClose={() => setSelectedSlip(null)}
      >
        {selectedSlip && (
          <View style={styles.modalOverlay}>
            <View style={styles.modalContent}>
              {/* Modal Header */}
              <View style={styles.modalHeader}>
                <View>
                  <Text style={styles.modalTitle}>SALARY PAY SLIP</Text>
                  <Text style={styles.modalSubtitle}>
                    {MONTH_NAMES[selectedSlip.month - 1]} {selectedSlip.year}
                  </Text>
                </View>
                <TouchableOpacity onPress={() => setSelectedSlip(null)}>
                  <X size={24} color={Colors.white} />
                </TouchableOpacity>
              </View>

              <ScrollView style={styles.modalBody} showsVerticalScrollIndicator={false}>
                {/* School & Staff Info */}
                <View style={styles.infoCard}>
                  <View style={styles.infoRow}>
                    <Building size={18} color={Colors.primary} style={{ marginRight: 10 }} />
                    <View style={{ flex: 1 }}>
                      <Text style={styles.infoTitle}>{selectedSlip.school?.name || 'Whiteleaf International School'}</Text>
                      <Text style={styles.infoSub}>{selectedSlip.school?.address || 'School Campus'}</Text>
                    </View>
                  </View>

                  <View style={styles.divider} />

                  <View style={styles.infoRow}>
                    <User size={18} color={Colors.primary} style={{ marginRight: 10 }} />
                    <View style={{ flex: 1 }}>
                      <Text style={styles.empName}>{selectedSlip.user?.name || 'Staff Member'}</Text>
                      <Text style={styles.infoSub}>
                        ID: {selectedSlip.user?.employeeId} • {selectedSlip.user?.designation || 'Staff'}
                      </Text>
                    </View>
                  </View>
                </View>

                {/* Attendance Summary */}
                <Text style={styles.sectionHeader}>ATTENDANCE STATISTICS</Text>
                <View style={styles.gridContainer}>
                  <View style={[styles.gridBox, { backgroundColor: '#ECFDF5', borderColor: '#A7F3D0' }]}>
                    <Text style={[styles.gridLabel, { color: '#047857' }]}>PRESENT</Text>
                    <Text style={[styles.gridVal, { color: '#065F46' }]}>{selectedSlip.presentDays} Days</Text>
                  </View>
                  <View style={[styles.gridBox, { backgroundColor: '#EEF2FF', borderColor: '#C7D2FE' }]}>
                    <Text style={[styles.gridLabel, { color: '#4338CA' }]}>PAID LEAVES</Text>
                    <Text style={[styles.gridVal, { color: '#3730A3' }]}>{selectedSlip.paidLeaveDays} Days</Text>
                  </View>
                  <View style={[styles.gridBox, { backgroundColor: '#FEF2F2', borderColor: '#FECACA' }]}>
                    <Text style={[styles.gridLabel, { color: '#B91C1C' }]}>UNPAID CUT</Text>
                    <Text style={[styles.gridVal, { color: '#991B1B' }]}>{selectedSlip.unpaidLeaveDays + selectedSlip.absentDays} Days</Text>
                  </View>
                  <View style={[styles.gridBox, { backgroundColor: '#F8FAFC', borderColor: '#E2E8F0' }]}>
                    <Text style={[styles.gridLabel, { color: '#64748B' }]}>TOTAL DAYS</Text>
                    <Text style={[styles.gridVal, { color: '#334155' }]}>{selectedSlip.totalDaysInMonth} Days</Text>
                  </View>
                </View>

                {/* Financial Calculation Table */}
                <Text style={styles.sectionHeader}>PAYROLL BREAKDOWN</Text>
                <View style={styles.tableCard}>
                  <View style={styles.tableRow}>
                    <Text style={styles.tableItem}>Base Monthly Salary</Text>
                    <Text style={styles.tableVal}>₹{selectedSlip.baseSalary.toLocaleString('en-IN')}</Text>
                  </View>
                  {selectedSlip.allowances > 0 && (
                    <View style={styles.tableRow}>
                      <Text style={[styles.tableItem, { color: Colors.success }]}>+ Allowances</Text>
                      <Text style={[styles.tableVal, { color: Colors.success }]}>+₹{selectedSlip.allowances.toLocaleString('en-IN')}</Text>
                    </View>
                  )}
                  {selectedSlip.bonus > 0 && (
                    <View style={styles.tableRow}>
                      <Text style={[styles.tableItem, { color: Colors.success }]}>+ Performance Bonus</Text>
                      <Text style={[styles.tableVal, { color: Colors.success }]}>+₹{selectedSlip.bonus.toLocaleString('en-IN')}</Text>
                    </View>
                  )}
                  {selectedSlip.deductions > 0 && (
                    <View style={styles.tableRow}>
                      <Text style={[styles.tableItem, { color: Colors.error }]}>- Leave & Absence Cuts</Text>
                      <Text style={[styles.tableVal, { color: Colors.error }]}>-₹{selectedSlip.deductions.toLocaleString('en-IN')}</Text>
                    </View>
                  )}

                  <View style={styles.totalRow}>
                    <Text style={styles.totalLabel}>NET PAYABLE SALARY</Text>
                    <Text style={styles.totalVal}>₹{selectedSlip.netSalary.toLocaleString('en-IN')}</Text>
                  </View>
                </View>

                {/* Payment Information */}
                <View style={styles.paymentBox}>
                  <Text style={styles.paymentLabel}>
                    Payment Status: <Text style={{ color: selectedSlip.status === 'PAID' ? Colors.success : Colors.warning, fontWeight: 'bold' }}>{selectedSlip.status}</Text>
                  </Text>
                  {selectedSlip.paymentMode && (
                    <Text style={styles.paymentSub}>Payment Mode: {selectedSlip.paymentMode}</Text>
                  )}
                  {selectedSlip.paymentDate && (
                    <Text style={styles.paymentSub}>
                      Date: {new Date(selectedSlip.paymentDate).toLocaleDateString('en-IN')}
                    </Text>
                  )}
                </View>

                <TouchableOpacity
                  style={styles.closeBtn}
                  onPress={() => setSelectedSlip(null)}
                >
                  <Text style={styles.closeBtnText}>Close Pay Slip</Text>
                </TouchableOpacity>
              </ScrollView>
            </View>
          </View>
        )}
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    ...typography.body2,
    color: Colors.textSecondary,
    marginTop: 12,
  },
  listContent: {
    padding: 16,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    elevation: 2,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  monthBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.background,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  monthText: {
    ...typography.subtitle2,
    color: Colors.primary,
    fontWeight: 'bold',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  paidBadge: {
    backgroundColor: '#ECFDF5',
  },
  pendingBadge: {
    backgroundColor: '#FEF3C7',
  },
  statusText: {
    ...typography.caption,
    fontWeight: 'bold',
  },
  paidText: {
    color: '#10B981',
  },
  pendingText: {
    color: '#F59E0B',
  },
  cardBody: {
    marginVertical: 4,
  },
  amountContainer: {
    marginBottom: 8,
  },
  amountLabel: {
    ...typography.caption,
    color: Colors.textSecondary,
  },
  amountValue: {
    ...typography.h2,
    color: Colors.primary,
    marginTop: 2,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statText: {
    ...typography.caption,
    color: Colors.textSecondary,
  },
  statHighlight: {
    fontWeight: 'bold',
    color: Colors.textPrimary,
  },
  statDot: {
    marginHorizontal: 8,
    color: Colors.textDisabled,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    paddingTop: 10,
    marginTop: 10,
  },
  viewDetailText: {
    ...typography.caption,
    color: Colors.primary,
    fontWeight: 'bold',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyTitle: {
    ...typography.h3,
    color: Colors.textPrimary,
    marginTop: 16,
  },
  emptySubtitle: {
    ...typography.body2,
    color: Colors.textSecondary,
    textAlign: 'center',
    marginHorizontal: 32,
    marginTop: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
    overflow: 'hidden',
  },
  modalHeader: {
    backgroundColor: Colors.primary,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: {
    ...typography.h3,
    color: Colors.white,
  },
  modalSubtitle: {
    ...typography.body2,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 2,
  },
  modalBody: {
    padding: 20,
  },
  infoCard: {
    backgroundColor: Colors.background,
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoTitle: {
    ...typography.subtitle1,
    color: Colors.textPrimary,
    fontWeight: 'bold',
  },
  empName: {
    ...typography.subtitle1,
    color: Colors.primary,
    fontWeight: 'bold',
  },
  infoSub: {
    ...typography.caption,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.borderLight,
    marginVertical: 10,
  },
  sectionHeader: {
    ...typography.subtitle2,
    color: Colors.textSecondary,
    marginBottom: 10,
    letterSpacing: 0.5,
  },
  gridContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  gridBox: {
    flex: 1,
    marginHorizontal: 3,
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
  },
  gridLabel: {
    fontSize: 9,
    fontWeight: 'bold',
  },
  gridVal: {
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: 4,
  },
  tableCard: {
    backgroundColor: Colors.background,
    borderRadius: 14,
    padding: 14,
    marginBottom: 20,
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  tableItem: {
    ...typography.body2,
    color: Colors.textPrimary,
  },
  tableVal: {
    ...typography.body2,
    fontWeight: 'bold',
    color: Colors.textPrimary,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 12,
    marginTop: 4,
  },
  totalLabel: {
    ...typography.subtitle1,
    fontWeight: 'bold',
    color: Colors.primary,
  },
  totalVal: {
    ...typography.h2,
    color: '#10B981',
  },
  paymentBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    marginBottom: 24,
  },
  paymentLabel: {
    ...typography.body2,
    color: Colors.textPrimary,
  },
  paymentSub: {
    ...typography.caption,
    color: Colors.textSecondary,
    marginTop: 4,
  },
  closeBtn: {
    backgroundColor: Colors.primary,
    height: 50,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  closeBtnText: {
    ...typography.button,
    color: Colors.white,
  },
});
